/** Catalog of installable DE / DB plugins and their connector forms */

export type PluginFieldKind = "text" | "password" | "number" | "select";

export interface PluginField {
  key: string;
  label: string;
  kind: PluginFieldKind;
  /** If true, value is stored encrypted via secretRef — never in YAML plaintext */
  secret?: boolean;
  required?: boolean;
  placeholder?: string;
  options?: Array<{ value: string; label: string }>;
  group: "connection" | "auth" | "target";
  help?: string;
}

export interface PluginDef {
  id: string;
  name: string;
  vendor: string;
  category: "database" | "warehouse" | "lake" | "streaming" | "platform" | "workflow" | "custom";
  description: string;
  /** Connector type written into workspace YAML */
  connectorType: string;
  accent: string;
  /** Short badge */
  badge: string;
  fields: PluginField[];
  /** Example node types unlocked after install */
  unlocks: string[];
  /** True when created by the customer (not built-in catalog) */
  custom?: boolean;
}

export const PLUGIN_CATALOG: PluginDef[] = [
  {
    id: "mongodb",
    name: "MongoDB",
    vendor: "MongoDB Inc.",
    category: "database",
    description:
      "Document DB — local, Atlas, or self-hosted. First-class reads, aggregates, change streams.",
    connectorType: "mongodb",
    accent: "#00ED64",
    badge: "MDB",
    unlocks: [
      "mongodb.read",
      "mongodb.write",
      "mongodb.aggregate",
      "mongodb.changestream",
    ],
    fields: [
      {
        key: "mode",
        label: "Deployment",
        kind: "select",
        group: "connection",
        required: true,
        options: [
          { value: "local", label: "Local" },
          { value: "atlas", label: "Atlas (SaaS)" },
          { value: "iaas", label: "Self-hosted / IaaS" },
        ],
      },
      {
        key: "uri",
        label: "Connection URI",
        kind: "password",
        secret: true,
        group: "connection",
        placeholder: "mongodb+srv://… or mongodb://localhost:27017",
        help: "Prefer URI; host fields used if URI empty",
      },
      {
        key: "host",
        label: "Host",
        kind: "text",
        group: "connection",
        placeholder: "localhost",
      },
      {
        key: "port",
        label: "Port",
        kind: "number",
        group: "connection",
        placeholder: "27017",
      },
      {
        key: "username",
        label: "Username",
        kind: "text",
        group: "auth",
      },
      {
        key: "password",
        label: "Password",
        kind: "password",
        secret: true,
        group: "auth",
      },
      {
        key: "database",
        label: "Database",
        kind: "text",
        group: "target",
        required: true,
        placeholder: "ops",
      },
      {
        key: "collection",
        label: "Default collection",
        kind: "text",
        group: "target",
        placeholder: "users",
      },
      {
        key: "authSource",
        label: "Auth source",
        kind: "text",
        group: "auth",
        placeholder: "admin",
      },
    ],
  },
  {
    id: "postgresql",
    name: "PostgreSQL",
    vendor: "PostgreSQL Global Development Group",
    category: "database",
    description: "Relational OLTP — RDS, Cloud SQL, self-hosted.",
    connectorType: "postgresql",
    accent: "#336791",
    badge: "PG",
    unlocks: ["postgresql.query", "postgresql.insert", "postgresql.execute"],
    fields: [
      {
        key: "host",
        label: "Host",
        kind: "text",
        group: "connection",
        required: true,
        placeholder: "db.example.com",
      },
      {
        key: "port",
        label: "Port",
        kind: "number",
        group: "connection",
        placeholder: "5432",
      },
      {
        key: "ssl",
        label: "SSL mode",
        kind: "select",
        group: "connection",
        options: [
          { value: "require", label: "require" },
          { value: "prefer", label: "prefer" },
          { value: "disable", label: "disable" },
        ],
      },
      {
        key: "username",
        label: "Username",
        kind: "text",
        group: "auth",
        required: true,
      },
      {
        key: "password",
        label: "Password",
        kind: "password",
        secret: true,
        group: "auth",
        required: true,
      },
      {
        key: "database",
        label: "Database",
        kind: "text",
        group: "target",
        required: true,
      },
      {
        key: "schema",
        label: "Schema",
        kind: "text",
        group: "target",
        placeholder: "public",
      },
      {
        key: "table",
        label: "Default table",
        kind: "text",
        group: "target",
        placeholder: "events",
      },
    ],
  },
  {
    id: "snowflake",
    name: "Snowflake",
    vendor: "Snowflake Inc.",
    category: "warehouse",
    description: "Cloud data warehouse — account, warehouse, DB/schema.",
    connectorType: "snowflake",
    accent: "#29B5E8",
    badge: "SF",
    unlocks: ["snowflake.query", "snowflake.load", "snowflake.unload"],
    fields: [
      {
        key: "account",
        label: "Account identifier",
        kind: "text",
        group: "connection",
        required: true,
        placeholder: "xy12345.us-east-1",
      },
      {
        key: "username",
        label: "Username",
        kind: "text",
        group: "auth",
        required: true,
      },
      {
        key: "password",
        label: "Password",
        kind: "password",
        secret: true,
        group: "auth",
      },
      {
        key: "token",
        label: "Programmatic access token",
        kind: "password",
        secret: true,
        group: "auth",
        help: "Optional PAT instead of password",
      },
      {
        key: "warehouse",
        label: "Warehouse",
        kind: "text",
        group: "target",
        required: true,
      },
      {
        key: "database",
        label: "Database",
        kind: "text",
        group: "target",
        required: true,
      },
      {
        key: "schema",
        label: "Schema",
        kind: "text",
        group: "target",
        placeholder: "PUBLIC",
      },
      {
        key: "role",
        label: "Role",
        kind: "text",
        group: "auth",
        placeholder: "SYSADMIN",
      },
    ],
  },
  {
    id: "bigquery",
    name: "Google BigQuery",
    vendor: "Google Cloud",
    category: "warehouse",
    description: "Serverless analytics warehouse — project, dataset, table.",
    connectorType: "bigquery",
    accent: "#4285F4",
    badge: "BQ",
    unlocks: ["bigquery.query", "bigquery.load", "bigquery.extract"],
    fields: [
      {
        key: "projectId",
        label: "GCP project ID",
        kind: "text",
        group: "connection",
        required: true,
      },
      {
        key: "location",
        label: "Location",
        kind: "select",
        group: "connection",
        options: [
          { value: "US", label: "US" },
          { value: "EU", label: "EU" },
          { value: "asia-south1", label: "asia-south1" },
        ],
      },
      {
        key: "serviceAccountJson",
        label: "Service account JSON",
        kind: "password",
        secret: true,
        group: "auth",
        required: true,
        placeholder: "{ \"type\": \"service_account\", … }",
      },
      {
        key: "dataset",
        label: "Dataset",
        kind: "text",
        group: "target",
        required: true,
      },
      {
        key: "table",
        label: "Default table",
        kind: "text",
        group: "target",
      },
    ],
  },
  {
    id: "kafka",
    name: "Apache Kafka",
    vendor: "Apache / Confluent",
    category: "streaming",
    description: "Event streaming — bootstrap servers, topic, SASL.",
    connectorType: "kafka",
    accent: "#231F20",
    badge: "KF",
    unlocks: ["kafka.consume", "kafka.produce"],
    fields: [
      {
        key: "bootstrapServers",
        label: "Bootstrap servers",
        kind: "text",
        group: "connection",
        required: true,
        placeholder: "broker:9092",
      },
      {
        key: "securityProtocol",
        label: "Security protocol",
        kind: "select",
        group: "connection",
        options: [
          { value: "PLAINTEXT", label: "PLAINTEXT" },
          { value: "SASL_SSL", label: "SASL_SSL" },
          { value: "SSL", label: "SSL" },
        ],
      },
      {
        key: "username",
        label: "SASL username / API key",
        kind: "text",
        group: "auth",
      },
      {
        key: "password",
        label: "SASL password / API secret",
        kind: "password",
        secret: true,
        group: "auth",
      },
      {
        key: "topic",
        label: "Default topic",
        kind: "text",
        group: "target",
        required: true,
      },
      {
        key: "groupId",
        label: "Consumer group",
        kind: "text",
        group: "target",
        placeholder: "agent-studio",
      },
    ],
  },
  {
    id: "s3",
    name: "Amazon S3",
    vendor: "AWS",
    category: "lake",
    description: "Object storage — keys, region, bucket, prefix for lakes.",
    connectorType: "s3",
    accent: "#FF9900",
    badge: "S3",
    unlocks: [
      "s3.list",
      "s3.read",
      "s3.write",
      "s3.delete",
      "s3.copy",
      "s3.createBucket",
      "s3.presign",
      "s3.head",
    ],
    fields: [
      {
        key: "region",
        label: "AWS region",
        kind: "text",
        group: "connection",
        required: true,
        placeholder: "us-east-1",
      },
      {
        key: "accessKeyId",
        label: "Access key ID",
        kind: "password",
        secret: true,
        group: "auth",
        required: true,
        help: "Stored in the connector secret (not YAML). Required for live S3.",
      },
      {
        key: "secretAccessKey",
        label: "Secret access key",
        kind: "password",
        secret: true,
        group: "auth",
        required: true,
      },
      {
        key: "sessionToken",
        label: "Session token (optional)",
        kind: "password",
        secret: true,
        group: "auth",
      },
      {
        key: "bucket",
        label: "Bucket",
        kind: "text",
        group: "target",
        required: true,
      },
      {
        key: "prefix",
        label: "Prefix / path",
        kind: "text",
        group: "target",
        placeholder: "raw/events/",
      },
    ],
  },
  {
    id: "databricks",
    name: "Databricks",
    vendor: "Databricks",
    category: "platform",
    description: "Lakehouse — workspace host, PAT, SQL warehouse, Unity Catalog.",
    connectorType: "databricks",
    accent: "#FF3621",
    badge: "DBX",
    unlocks: ["databricks.sql", "databricks.notebook", "databricks.volume"],
    fields: [
      {
        key: "host",
        label: "Workspace host",
        kind: "text",
        group: "connection",
        required: true,
        placeholder: "adb-xxxx.azuredatabricks.net",
      },
      {
        key: "httpPath",
        label: "SQL warehouse HTTP path",
        kind: "text",
        group: "connection",
        required: true,
        placeholder: "/sql/1.0/warehouses/…",
      },
      {
        key: "token",
        label: "Personal access token",
        kind: "password",
        secret: true,
        group: "auth",
        required: true,
      },
      {
        key: "catalog",
        label: "Catalog",
        kind: "text",
        group: "target",
        placeholder: "main",
      },
      {
        key: "schema",
        label: "Schema",
        kind: "text",
        group: "target",
        placeholder: "default",
      },
      {
        key: "table",
        label: "Default table",
        kind: "text",
        group: "target",
      },
    ],
  },
  {
    id: "clickhouse",
    name: "ClickHouse",
    vendor: "ClickHouse Inc.",
    category: "database",
    description: "OLAP column store — analytics tables at speed.",
    connectorType: "clickhouse",
    accent: "#FFCC01",
    badge: "CH",
    unlocks: [
      "clickhouse.query",
      "clickhouse.insert",
      "clickhouse.execute",
      "clickhouse.createTable",
      "clickhouse.createDatabase",
      "clickhouse.listTables",
      "clickhouse.truncate",
    ],
    fields: [
      {
        key: "host",
        label: "Host",
        kind: "text",
        group: "connection",
        required: true,
        placeholder: "clickhouse.example.com",
      },
      {
        key: "port",
        label: "HTTP port",
        kind: "number",
        group: "connection",
        placeholder: "8443",
      },
      {
        key: "username",
        label: "Username",
        kind: "text",
        group: "auth",
        required: true,
        placeholder: "default",
      },
      {
        key: "password",
        label: "Password",
        kind: "password",
        secret: true,
        group: "auth",
      },
      {
        key: "database",
        label: "Database",
        kind: "text",
        group: "target",
        required: true,
      },
      {
        key: "table",
        label: "Default table",
        kind: "text",
        group: "target",
      },
    ],
  },
  {
    id: "redis",
    name: "Redis",
    vendor: "Redis Ltd.",
    category: "database",
    description: "In-memory key-value — cache, streams, and pub/sub for pipelines.",
    connectorType: "redis",
    accent: "#DC382D",
    badge: "RDS",
    unlocks: ["redis.get", "redis.set", "redis.streamRead"],
    fields: [
      {
        key: "host",
        label: "Host",
        kind: "text",
        group: "connection",
        required: true,
        placeholder: "localhost",
      },
      {
        key: "port",
        label: "Port",
        kind: "number",
        group: "connection",
        placeholder: "6379",
      },
      {
        key: "username",
        label: "Username",
        kind: "text",
        group: "auth",
        placeholder: "default",
      },
      {
        key: "password",
        label: "Password / ACL token",
        kind: "password",
        secret: true,
        group: "auth",
      },
      {
        key: "db",
        label: "Database index",
        kind: "number",
        group: "target",
        placeholder: "0",
      },
      {
        key: "keyPrefix",
        label: "Key prefix",
        kind: "text",
        group: "target",
        placeholder: "pipeline:",
      },
    ],
  },
  {
    id: "elasticsearch",
    name: "Elasticsearch",
    vendor: "Elastic",
    category: "database",
    description: "Search & analytics engine — indexes, queries, and bulk ingest.",
    connectorType: "elasticsearch",
    accent: "#FEC514",
    badge: "ES",
    unlocks: ["elasticsearch.search", "elasticsearch.bulk", "elasticsearch.index"],
    fields: [
      {
        key: "url",
        label: "Cluster URL",
        kind: "text",
        group: "connection",
        required: true,
        placeholder: "https://localhost:9200",
      },
      {
        key: "verifySsl",
        label: "Verify TLS certificate",
        kind: "select",
        group: "connection",
        options: [
          { value: "", label: "Auto (skip for localhost)" },
          { value: "true", label: "Verify" },
          { value: "false", label: "Allow self-signed" },
        ],
        help: "Elasticsearch 8 / OpenSearch ship a self-signed certificate by default",
      },
      {
        key: "caCertPath",
        label: "CA bundle path",
        kind: "text",
        group: "connection",
        placeholder: "/path/to/http_ca.crt",
      },
      {
        key: "apiKey",
        label: "API key",
        kind: "password",
        secret: true,
        group: "auth",
        help: "Preferred over basic auth when available",
      },
      {
        key: "username",
        label: "Username",
        kind: "text",
        group: "auth",
      },
      {
        key: "password",
        label: "Password",
        kind: "password",
        secret: true,
        group: "auth",
      },
      {
        key: "index",
        label: "Default index",
        kind: "text",
        group: "target",
        required: true,
        placeholder: "events-*",
      },
    ],
  },
  {
    id: "mysql",
    name: "MySQL",
    vendor: "Oracle / Community",
    category: "database",
    description: "Relational OLTP — RDS, Aurora, Cloud SQL, or self-hosted.",
    connectorType: "mysql",
    accent: "#00758F",
    badge: "SQL",
    unlocks: ["mysql.query", "mysql.insert", "mysql.cdc"],
    fields: [
      {
        key: "host",
        label: "Host",
        kind: "text",
        group: "connection",
        required: true,
        placeholder: "localhost",
      },
      {
        key: "port",
        label: "Port",
        kind: "number",
        group: "connection",
        placeholder: "3306",
      },
      {
        key: "username",
        label: "Username",
        kind: "text",
        group: "auth",
        required: true,
      },
      {
        key: "password",
        label: "Password",
        kind: "password",
        secret: true,
        group: "auth",
        required: true,
      },
      {
        key: "database",
        label: "Database",
        kind: "text",
        group: "target",
        required: true,
      },
      {
        key: "table",
        label: "Default table",
        kind: "text",
        group: "target",
      },
    ],
  },
  {
    id: "redshift",
    name: "Amazon Redshift",
    vendor: "Amazon Web Services",
    category: "warehouse",
    description: "Cloud data warehouse — clusters, Spectrum, and UNLOAD to S3.",
    connectorType: "redshift",
    accent: "#8C4FFF",
    badge: "RS",
    unlocks: ["redshift.query", "redshift.copy", "redshift.unload"],
    fields: [
      {
        key: "host",
        label: "Cluster endpoint",
        kind: "text",
        group: "connection",
        required: true,
        placeholder: "cluster.xxxx.region.redshift.amazonaws.com",
      },
      {
        key: "port",
        label: "Port",
        kind: "number",
        group: "connection",
        placeholder: "5439",
      },
      {
        key: "username",
        label: "Username",
        kind: "text",
        group: "auth",
        required: true,
      },
      {
        key: "password",
        label: "Password",
        kind: "password",
        secret: true,
        group: "auth",
        required: true,
      },
      {
        key: "database",
        label: "Database",
        kind: "text",
        group: "target",
        required: true,
        placeholder: "dev",
      },
      {
        key: "schema",
        label: "Schema",
        kind: "text",
        group: "target",
        placeholder: "public",
      },
      {
        key: "table",
        label: "Default table",
        kind: "text",
        group: "target",
      },
    ],
  },
  {
    id: "azure_blob",
    name: "Azure Blob Storage",
    vendor: "Microsoft Azure",
    category: "lake",
    description: "Object storage / ADLS Gen2 — containers, paths, and SAS auth.",
    connectorType: "azure_blob",
    accent: "#0078D4",
    badge: "AZ",
    unlocks: ["azure_blob.read", "azure_blob.write", "azure_blob.list"],
    fields: [
      {
        key: "accountName",
        label: "Storage account",
        kind: "text",
        group: "connection",
        required: true,
        placeholder: "mystorageacct",
      },
      {
        key: "endpointSuffix",
        label: "Endpoint suffix",
        kind: "text",
        group: "connection",
        placeholder: "core.windows.net",
      },
      {
        key: "accountKey",
        label: "Account key",
        kind: "password",
        secret: true,
        group: "auth",
      },
      {
        key: "sasToken",
        label: "SAS token",
        kind: "password",
        secret: true,
        group: "auth",
        help: "Use key or SAS — not both required",
      },
      {
        key: "container",
        label: "Container",
        kind: "text",
        group: "target",
        required: true,
      },
      {
        key: "prefix",
        label: "Prefix / path",
        kind: "text",
        group: "target",
        placeholder: "raw/events/",
      },
    ],
  },
  {
    id: "gcs",
    name: "Google Cloud Storage",
    vendor: "Google Cloud",
    category: "lake",
    description: "GCS buckets for lake / landing zone objects and Parquet.",
    connectorType: "gcs",
    accent: "#4285F4",
    badge: "GCS",
    unlocks: ["gcs.read", "gcs.write", "gcs.list"],
    fields: [
      {
        key: "projectId",
        label: "Project ID",
        kind: "text",
        group: "connection",
        required: true,
      },
      {
        key: "serviceAccountJson",
        label: "Service account JSON",
        kind: "password",
        secret: true,
        group: "auth",
        required: true,
        placeholder: "{ … }",
      },
      {
        key: "bucket",
        label: "Bucket",
        kind: "text",
        group: "target",
        required: true,
      },
      {
        key: "prefix",
        label: "Prefix / path",
        kind: "text",
        group: "target",
        placeholder: "landing/",
      },
    ],
  },
  {
    id: "neo4j",
    name: "Neo4j",
    vendor: "Neo4j Inc.",
    category: "database",
    description: "Graph database — Cypher queries, nodes, and relationships.",
    connectorType: "neo4j",
    accent: "#008CC1",
    badge: "N4J",
    unlocks: ["neo4j.cypher", "neo4j.write"],
    fields: [
      {
        key: "uri",
        label: "Bolt URI",
        kind: "text",
        group: "connection",
        required: true,
        placeholder: "neo4j+s://xxxx.databases.neo4j.io",
      },
      {
        key: "username",
        label: "Username",
        kind: "text",
        group: "auth",
        required: true,
        placeholder: "neo4j",
      },
      {
        key: "password",
        label: "Password",
        kind: "password",
        secret: true,
        group: "auth",
        required: true,
      },
      {
        key: "database",
        label: "Database",
        kind: "text",
        group: "target",
        placeholder: "neo4j",
      },
    ],
  },
  {
    id: "cassandra",
    name: "Apache Cassandra",
    vendor: "Apache / DataStax",
    category: "database",
    description: "Wide-column NoSQL — keyspaces, tables, and CQL.",
    connectorType: "cassandra",
    accent: "#1287B1",
    badge: "C*",
    unlocks: ["cassandra.query", "cassandra.insert"],
    fields: [
      {
        key: "contactPoints",
        label: "Contact points",
        kind: "text",
        group: "connection",
        required: true,
        placeholder: "127.0.0.1,127.0.0.2",
      },
      {
        key: "port",
        label: "Port",
        kind: "number",
        group: "connection",
        placeholder: "9042",
      },
      {
        key: "username",
        label: "Username",
        kind: "text",
        group: "auth",
      },
      {
        key: "password",
        label: "Password",
        kind: "password",
        secret: true,
        group: "auth",
      },
      {
        key: "keyspace",
        label: "Keyspace",
        kind: "text",
        group: "target",
        required: true,
      },
      {
        key: "table",
        label: "Default table",
        kind: "text",
        group: "target",
      },
    ],
  },
  {
    id: "duckdb",
    name: "DuckDB",
    vendor: "DuckDB Foundation",
    category: "database",
    description: "Embedded analytics OLAP — local files, Parquet, and MotherDuck.",
    connectorType: "duckdb",
    accent: "#FFF000",
    badge: "DUCK",
    unlocks: ["duckdb.query", "duckdb.import"],
    fields: [
      {
        key: "path",
        label: "Database path / MotherDuck",
        kind: "text",
        group: "connection",
        required: true,
        placeholder: "./analytics.duckdb or md:my_db",
      },
      {
        key: "token",
        label: "MotherDuck token",
        kind: "password",
        secret: true,
        group: "auth",
        help: "Only for MotherDuck cloud connections",
      },
      {
        key: "schema",
        label: "Schema",
        kind: "text",
        group: "target",
        placeholder: "main",
      },
      {
        key: "table",
        label: "Default table",
        kind: "text",
        group: "target",
      },
    ],
  },
  {
    id: "trino",
    name: "Trino",
    vendor: "Trino Software Foundation",
    category: "platform",
    description: "Federated SQL engine — query across warehouses, lakes, and DBs.",
    connectorType: "trino",
    accent: "#DD00A1",
    badge: "TRN",
    unlocks: ["trino.query"],
    fields: [
      {
        key: "host",
        label: "Coordinator host",
        kind: "text",
        group: "connection",
        required: true,
        placeholder: "trino.example.com",
      },
      {
        key: "port",
        label: "Port",
        kind: "number",
        group: "connection",
        placeholder: "8080",
      },
      {
        key: "username",
        label: "Username",
        kind: "text",
        group: "auth",
        required: true,
      },
      {
        key: "password",
        label: "Password / JWT",
        kind: "password",
        secret: true,
        group: "auth",
      },
      {
        key: "catalog",
        label: "Catalog",
        kind: "text",
        group: "target",
        required: true,
        placeholder: "hive",
      },
      {
        key: "schema",
        label: "Schema",
        kind: "text",
        group: "target",
        placeholder: "default",
      },
      {
        key: "table",
        label: "Default table",
        kind: "text",
        group: "target",
      },
    ],
  },
  {
    id: "airflow",
    name: "Apache Airflow",
    vendor: "Apache Software Foundation",
    category: "workflow",
    description:
      "Workflow orchestration — trigger DAGs, poll task status, XCom & connections.",
    connectorType: "airflow",
    accent: "#017CEE",
    badge: "AF",
    unlocks: [
      "airflow.triggerDag",
      "airflow.dagStatus",
      "airflow.xcomPull",
      "airflow.xcomPush",
      "airflow.listDags",
      "airflow.pauseDag",
      "airflow.clearTask",
      "airflow.importVariables",
    ],
    fields: [
      {
        key: "baseUrl",
        label: "Airflow API URL",
        kind: "text",
        group: "connection",
        required: true,
        placeholder: "https://airflow.example.com",
        help: "Webserver URL — /api/v2, /api/v1 or /api/experimental is added from the API version",
      },
      {
        key: "apiVersion",
        label: "Airflow version",
        kind: "select",
        group: "connection",
        options: [
          { value: "", label: "Auto-detect" },
          { value: "3", label: "Airflow 3.x (/api/v2, JWT)" },
          { value: "2", label: "Airflow 2.x (/api/v1)" },
          { value: "1", label: "Airflow 1.10 (/api/experimental)" },
        ],
      },
      {
        key: "username",
        label: "Username",
        kind: "text",
        group: "auth",
      },
      {
        key: "password",
        label: "Password",
        kind: "password",
        secret: true,
        group: "auth",
      },
      {
        key: "token",
        label: "API token",
        kind: "password",
        secret: true,
        group: "auth",
        help: "Use token or username/password",
      },
      {
        key: "dagId",
        label: "Default DAG ID",
        kind: "text",
        group: "target",
        placeholder: "etl_daily",
      },
      {
        key: "connectionId",
        label: "Airflow connection ID",
        kind: "text",
        group: "target",
        placeholder: "mongo_default",
      },
    ],
  },
  {
    id: "prefect",
    name: "Prefect",
    vendor: "Prefect Technologies",
    category: "workflow",
    description:
      "Modern orchestration — deploy flows, trigger runs, and read work pools.",
    connectorType: "prefect",
    accent: "#2D6DF6",
    badge: "PRF",
    unlocks: [
      "prefect.triggerDeployment",
      "prefect.runStatus",
      "prefect.listDeployments",
      "prefect.cancelRun",
      "prefect.setVariable",
      "prefect.readVariable",
      "prefect.workPoolStatus",
    ],
    fields: [
      {
        key: "apiUrl",
        label: "API URL",
        kind: "text",
        group: "connection",
        required: true,
        placeholder: "https://api.prefect.cloud/api/accounts/…/workspaces/…",
      },
      {
        key: "apiKey",
        label: "API key",
        kind: "password",
        secret: true,
        group: "auth",
        required: true,
        placeholder: "pnu_…",
        help: "Required — encrypted on Apply / Run, never written to YAML",
      },
      {
        key: "accountId",
        label: "Account ID",
        kind: "text",
        group: "target",
      },
      {
        key: "workspaceId",
        label: "Workspace ID",
        kind: "text",
        group: "target",
      },
      {
        key: "deploymentName",
        label: "Default deployment",
        kind: "text",
        group: "target",
        placeholder: "my-flow/prod",
      },
    ],
  },
  {
    id: "dagster",
    name: "Dagster",
    vendor: "Dagster Labs",
    category: "workflow",
    description:
      "Asset-centric pipelines — launch jobs, materializations, and sensors.",
    connectorType: "dagster",
    accent: "#4F43DD",
    badge: "DG",
    unlocks: ["dagster.launchRun", "dagster.materialize"],
    fields: [
      {
        key: "graphqlUrl",
        label: "GraphQL / webserver URL",
        kind: "text",
        group: "connection",
        required: true,
        placeholder: "https://dagster.example.com/graphql",
      },
      {
        key: "token",
        label: "API token",
        kind: "password",
        secret: true,
        group: "auth",
        required: true,
      },
      {
        key: "repositoryLocation",
        label: "Code location",
        kind: "text",
        group: "target",
        placeholder: "my_location",
      },
      {
        key: "jobName",
        label: "Default job / asset job",
        kind: "text",
        group: "target",
      },
      {
        key: "repositoryName",
        label: "Repository name",
        kind: "text",
        group: "target",
        placeholder: "__repository__",
      },
    ],
  },
  {
    id: "dbt",
    name: "dbt",
    vendor: "dbt Labs",
    category: "workflow",
    description:
      "Analytics engineering — run models, tests, and docs against your warehouse.",
    connectorType: "dbt",
    accent: "#FF694B",
    badge: "DBT",
    unlocks: ["dbt.run", "dbt.test", "dbt.build"],
    fields: [
      {
        key: "mode",
        label: "Mode",
        kind: "select",
        group: "connection",
        required: true,
        options: [
          { value: "core", label: "dbt Core (CLI)" },
          { value: "cloud", label: "dbt Cloud API" },
        ],
      },
      {
        key: "projectDir",
        label: "Project directory",
        kind: "text",
        group: "connection",
        placeholder: "./dbt_project",
      },
      {
        key: "dbtPath",
        label: "dbt executable (Core)",
        kind: "text",
        group: "connection",
        placeholder: "dbt, dbtf or /path/to/venv/bin/dbt",
        help: "Flags are chosen from `dbt --version` (dbt 0.x, 1.x and Fusion supported)",
      },
      {
        key: "profilesDir",
        label: "Profiles directory (Core)",
        kind: "text",
        group: "connection",
        placeholder: "~/.dbt",
      },
      {
        key: "baseUrl",
        label: "dbt Cloud host",
        kind: "text",
        group: "connection",
        placeholder: "https://cloud.getdbt.com (or emea.dbt.com / <prefix>.us1.dbt.com)",
      },
      {
        key: "accountId",
        label: "dbt Cloud account ID",
        kind: "text",
        group: "connection",
      },
      {
        key: "apiToken",
        label: "dbt Cloud API token",
        kind: "password",
        secret: true,
        group: "auth",
      },
      {
        key: "jobId",
        label: "Cloud job ID",
        kind: "text",
        group: "target",
      },
      {
        key: "select",
        label: "Default select / models",
        kind: "text",
        group: "target",
        placeholder: "tag:daily+",
      },
      {
        key: "target",
        label: "Profile target",
        kind: "text",
        group: "target",
        placeholder: "prod",
      },
    ],
  },
  {
    id: "spark",
    name: "Apache Spark",
    vendor: "Apache Software Foundation",
    category: "workflow",
    description:
      "Distributed compute — submit jobs to Spark clusters / Databricks / EMR.",
    connectorType: "spark",
    accent: "#E25A1C",
    badge: "SPK",
    unlocks: [
      "spark.submit",
      "spark.sql",
      "spark.jobStatus",
      "spark.createTable",
      "spark.read",
      "spark.write",
      "spark.cancel",
    ],
    fields: [
      {
        key: "master",
        label: "Master URL",
        kind: "text",
        group: "connection",
        required: true,
        placeholder: "spark://host:7077 or yarn / k8s",
      },
      {
        key: "restUrl",
        label: "REST URL (status / kill)",
        kind: "text",
        group: "connection",
        placeholder: "http://host:6066",
        help: "n8n Spark credential restUrl — derived from spark://host:7077 when empty",
      },
      {
        key: "deployMode",
        label: "Deploy mode",
        kind: "select",
        group: "connection",
        options: [
          { value: "client", label: "Client" },
          { value: "cluster", label: "Cluster" },
        ],
      },
      {
        key: "token",
        label: "Auth token / Kerberos keytab ref",
        kind: "password",
        secret: true,
        group: "auth",
      },
      {
        key: "appName",
        label: "Default app name",
        kind: "text",
        group: "target",
        placeholder: "agent-studio-job",
      },
      {
        key: "mainClass",
        label: "Main class / entry",
        kind: "text",
        group: "target",
      },
      {
        key: "jarOrPy",
        label: "JAR / Python file path",
        kind: "text",
        group: "target",
        placeholder: "s3://bucket/jobs/etl.py",
      },
    ],
  },
  {
    id: "flink",
    name: "Apache Flink",
    vendor: "Apache Software Foundation",
    category: "workflow",
    description:
      "Stateful stream processing — submit jobs and manage Flink clusters.",
    connectorType: "flink",
    accent: "#E6526F",
    badge: "FLK",
    unlocks: ["flink.submit", "flink.jobStatus"],
    fields: [
      {
        key: "restUrl",
        label: "JobManager REST URL",
        kind: "text",
        group: "connection",
        required: true,
        placeholder: "http://flink-jm:8081",
      },
      {
        key: "username",
        label: "Username",
        kind: "text",
        group: "auth",
      },
      {
        key: "password",
        label: "Password / token",
        kind: "password",
        secret: true,
        group: "auth",
      },
      {
        key: "jobJar",
        label: "Default job JAR / artifact",
        kind: "text",
        group: "target",
      },
      {
        key: "parallelism",
        label: "Default parallelism",
        kind: "number",
        group: "target",
        placeholder: "4",
      },
    ],
  },
  {
    id: "airbyte",
    name: "Airbyte",
    vendor: "Airbyte",
    category: "workflow",
    description:
      "Open ELT — sync connections, sources, and destinations via API.",
    connectorType: "airbyte",
    accent: "#615EFF",
    badge: "AB",
    unlocks: ["airbyte.triggerSync", "airbyte.syncStatus"],
    fields: [
      {
        key: "apiUrl",
        label: "Airbyte API URL",
        kind: "text",
        group: "connection",
        required: true,
        placeholder: "https://api.airbyte.com/v1 or http://localhost:8000/api/v1",
      },
      {
        key: "clientId",
        label: "Client ID",
        kind: "text",
        group: "auth",
      },
      {
        key: "clientSecret",
        label: "Client secret / API key",
        kind: "password",
        secret: true,
        group: "auth",
        required: true,
      },
      {
        key: "workspaceId",
        label: "Workspace ID",
        kind: "text",
        group: "target",
        required: true,
      },
      {
        key: "connectionId",
        label: "Default connection ID",
        kind: "text",
        group: "target",
      },
    ],
  },
  {
    id: "nifi",
    name: "Apache NiFi",
    vendor: "Apache Software Foundation",
    category: "workflow",
    description:
      "Visual dataflow — start/stop process groups and monitor queues.",
    connectorType: "nifi",
    accent: "#728E9B",
    badge: "NIFI",
    unlocks: ["nifi.startProcessGroup", "nifi.stopProcessGroup", "nifi.provenance"],
    fields: [
      {
        key: "baseUrl",
        label: "NiFi API URL",
        kind: "text",
        group: "connection",
        required: true,
        placeholder: "https://nifi.example.com/nifi-api",
      },
      {
        key: "nifiVersion",
        label: "NiFi version",
        kind: "select",
        group: "connection",
        options: [
          { value: "", label: "Auto-detect" },
          { value: "2", label: "NiFi 2.x (parameter contexts)" },
          { value: "1", label: "NiFi 1.x (variable registry)" },
        ],
        help: "Update Variables uses the variable registry on 1.x and parameter contexts on 2.x",
      },
      {
        key: "username",
        label: "Username",
        kind: "text",
        group: "auth",
      },
      {
        key: "password",
        label: "Password",
        kind: "password",
        secret: true,
        group: "auth",
      },
      {
        key: "token",
        label: "Bearer token",
        kind: "password",
        secret: true,
        group: "auth",
      },
      {
        key: "verifySsl",
        label: "Verify TLS certificate",
        kind: "select",
        group: "connection",
        options: [
          { value: "", label: "Auto (skip for localhost)" },
          { value: "true", label: "Verify" },
          { value: "false", label: "Allow self-signed" },
        ],
        help: "NiFi ships a self-signed certificate — choose Allow self-signed or set a CA bundle",
      },
      {
        key: "caCertPath",
        label: "CA bundle path",
        kind: "text",
        group: "connection",
        placeholder: "/path/to/nifi-ca.pem",
      },
      {
        key: "processGroupId",
        label: "Default process group ID",
        kind: "text",
        group: "target",
      },
    ],
  },
  {
    id: "great_expectations",
    name: "Great Expectations",
    vendor: "GX / Great Expectations",
    category: "workflow",
    description:
      "Data quality — validate suites, checkpoints, and expectation results.",
    connectorType: "great_expectations",
    accent: "#FF5511",
    badge: "GX",
    unlocks: ["great_expectations.validate", "great_expectations.checkpoint"],
    fields: [
      {
        key: "contextRoot",
        label: "GX project / context root",
        kind: "text",
        group: "connection",
        required: true,
        placeholder: "./gx",
      },
      {
        key: "cloudMode",
        label: "Mode",
        kind: "select",
        group: "connection",
        options: [
          { value: "local", label: "Local / OSS" },
          { value: "cloud", label: "GX Cloud" },
        ],
      },
      {
        key: "accessToken",
        label: "GX Cloud access token",
        kind: "password",
        secret: true,
        group: "auth",
      },
      {
        key: "organizationId",
        label: "Organization ID",
        kind: "text",
        group: "target",
      },
      {
        key: "checkpointName",
        label: "Default checkpoint",
        kind: "text",
        group: "target",
        placeholder: "daily_checkpoint",
      },
      {
        key: "expectationSuite",
        label: "Expectation suite",
        kind: "text",
        group: "target",
      },
    ],
  },
  {
    id: "temporal",
    name: "Temporal",
    vendor: "Temporal Technologies",
    category: "workflow",
    description:
      "Durable execution — start workflows, signals, and query running runs.",
    connectorType: "temporal",
    accent: "#444CE7",
    badge: "TMP",
    unlocks: ["temporal.startWorkflow", "temporal.signal", "temporal.query"],
    fields: [
      {
        key: "address",
        label: "Frontend address",
        kind: "text",
        group: "connection",
        required: true,
        placeholder: "localhost:7233",
      },
      {
        key: "namespace",
        label: "Namespace",
        kind: "text",
        group: "connection",
        required: true,
        placeholder: "default",
      },
      {
        key: "apiKey",
        label: "API key (Temporal Cloud)",
        kind: "password",
        secret: true,
        group: "auth",
      },
      {
        key: "tlsCert",
        label: "mTLS client cert (PEM)",
        kind: "password",
        secret: true,
        group: "auth",
      },
      {
        key: "tlsKey",
        label: "mTLS client key (PEM)",
        kind: "password",
        secret: true,
        group: "auth",
        help: "Required with the client cert for Temporal Cloud mTLS namespaces",
      },
      {
        key: "taskQueue",
        label: "Default task queue",
        kind: "text",
        group: "target",
        required: true,
        placeholder: "agent-studio",
      },
      {
        key: "workflowType",
        label: "Default workflow type",
        kind: "text",
        group: "target",
      },
    ],
  },
];

export function getPlugin(id: string): PluginDef | undefined {
  return getAllPlugins().find((p) => p.id === id);
}

export const PLUGIN_STORAGE_KEY = "vynelix-installed-plugins";
export const CUSTOM_PLUGIN_STORAGE_KEY = "vynelix-custom-plugins";

export function loadCustomPlugins(): PluginDef[] {
  try {
    const raw = localStorage.getItem(CUSTOM_PLUGIN_STORAGE_KEY);
    if (!raw) return [];
    const parsed = JSON.parse(raw) as PluginDef[];
    return Array.isArray(parsed)
      ? parsed.filter((p) => p && typeof p.id === "string" && Array.isArray(p.fields))
      : [];
  } catch {
    return [];
  }
}

export function saveCustomPlugins(plugins: PluginDef[]) {
  localStorage.setItem(CUSTOM_PLUGIN_STORAGE_KEY, JSON.stringify(plugins));
}

/** Built-in catalog + customer-defined dynamic plugins */
export function getAllPlugins(): PluginDef[] {
  const custom = typeof localStorage !== "undefined" ? loadCustomPlugins() : [];
  const builtinIds = new Set(PLUGIN_CATALOG.map((p) => p.id));
  // Custom overrides same id only if explicitly custom (avoid collisions with builtins)
  const safeCustom = custom.filter((p) => !builtinIds.has(p.id) || p.custom);
  return [...PLUGIN_CATALOG, ...safeCustom.filter((p) => !builtinIds.has(p.id))];
}

export function upsertCustomPlugin(plugin: PluginDef): PluginDef {
  const next = {
    ...plugin,
    custom: true,
    category: plugin.category || ("custom" as const),
  };
  const existing = loadCustomPlugins().filter((p) => p.id !== next.id);
  // Never overwrite a built-in id
  if (PLUGIN_CATALOG.some((p) => p.id === next.id)) {
    throw new Error(`Plugin id “${next.id}” is reserved by a built-in plugin`);
  }
  saveCustomPlugins([...existing, next]);
  return next;
}

export function deleteCustomPlugin(id: string) {
  saveCustomPlugins(loadCustomPlugins().filter((p) => p.id !== id));
}

/** Slugify a display name into a stable plugin / connector id */
export function slugifyPluginId(name: string): string {
  return (
    name
      .trim()
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "_")
      .replace(/^_|_$/g, "")
      .slice(0, 48) || `custom_${Date.now().toString(36)}`
  );
}

export function createEmptyCustomField(): PluginField {
  return {
    key: "",
    label: "",
    kind: "text",
    group: "connection",
    required: false,
    secret: false,
  };
}
